apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: p7-gateway-pool
spec:
  blocks:
    - start: 172.23.22.240
      stop: 172.23.22.250
  serviceSelector:
    matchExpressions:
      - key: gateway.envoyproxy.io/owning-gateway-name
        operator: In
        values: ["p7-gw", "crownlabs-gw"]
      - key: gateway.envoyproxy.io/owning-gateway-namespace
        operator: In
        values: ["p7-demo", "envoy-gateway-system"]
